name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hacer checkout
      uses: actions/checkout@v4

    - name: Loguearse en Docker
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Construyendo la imagen
      run: docker build -t esrora/calculadora:latest .
    - name: Subiendo imagen
      run: docker push esrora/calculadora:latest
      
